server:
  port: 8095

spring:
  h2:
    console:
      enabled: true

  mail:
    host: emailhost
    port: 14141
    username: email@tost.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://test.com
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: app
      principal-attribute: preferred_username

